SELECT * FROM SALESDATACSV

-------------TOTAL SALES PER CATEGORY OF PRODUCTS----------------
SELECT SUM (TOTAL_SALES) AS SHIRT_CATEGORY FROM SALESDATACSV WHERE PRODUCT = 'SHIRT'
SELECT SUM (TOTAL_SALES) AS SHOES_CATEGORY FROM SALESDATACSV WHERE PRODUCT = 'SHOES'
SELECT SUM (TOTAL_SALES) AS HAT_CATEGORY FROM SALESDATACSV WHERE PRODUCT ='HAT'
SELECT SUM (TOTAL_SALES) AS SOCKS_CATEGORY FROM SALESDATACSV WHERE PRODUCT = 'SOCKS'
SELECT SUM (TOTAL_SALES) AS JACKETS_CATEGORY FROM SALESDATACSV WHERE PRODUCT = 'JACKET'
SELECT SUM (TOTAL_SALES) AS GLOVES_CATEGORY FROM SALESDATACSV WHERE PRODUCT = 'GLOVES'

------------NUMBER OF SALES TRANSACTIONS PER REGION----------------
SELECT COUNT (QUANTITY) AS NORTHSALES FROM SALESDATACSV WHERE REGION = 'NORTH'
SELECT COUNT (QUANTITY) AS SOUTHSALES FROM SALESDATACSV WHERE REGION = 'SOUTH'
SELECT COUNT (QUANTITY) AS EASTSALES FROM SALESDATACSV WHERE REGION = 'EAST'
SELECT COUNT (QUANTITY) AS WESTSALES FROM SALESDATACSV WHERE REGION = 'WEST'

------------HIGHEST SELLING PRODUCT (HSP) BY TOTAL SALES VALUE------------
SELECT TOP 1 PRODUCT,
SUM (TOTAL_SALES) AS GRAND_TOTAL_SALES FROM SALESDATACSV
GROUP BY Product

-----------TOTAL REVENUE PER PRODUCT -------------
SELECT PRODUCT, SUM (TOTAL_SALES) AS GRAND_TOTAL_SALES FROM SALESDATACSV
GROUP BY Product

SELECT * FROM SALESDATACSV

-----------MONTHLY SALES FOR 2024 -----------
SELECT FORMAT (ORDERDATE, '2024-MM') AS CURRENT_YEAR, SUM (TOTAL_SALES) AS MONTHLY_SALES
FROM SALESDATACSV
WHERE YEAR(ORDERDATE) = YEAR(GETDATE())
GROUP BY FORMAT (ORDERDATE, '2024-MM')
ORDER BY (CURRENT_YEAR)

-----------TOP 5 CUSTOMERS BY TOTAL PURCHASE AMOUNT---------
SELECT TOP 5 (CUSTOMER_ID), SUM (TOTAL_SALES) AS TOTAL_PURCHASE_AMOUNT
FROM SALESDATACSV
GROUP BY Customer_Id
ORDER BY TOTAL_PURCHASE_AMOUNT DESC

----------PERCENTAGE OF TOTAL SALES PER REGION-------
SELECT REGION, SUM (TOTAL_SALES) AS REGION_TOTAL_SALES,
(SUM (TOTAL_SALES) * 100 / (SELECT SUM (TOTAL_SALES) FROM SALESDATACSV)) AS REGIONAL_SALES_PERCENTAGE
FROM SALESDATACSV
GROUP BY Region
ORDER BY REGIONAL_SALES_PERCENTAGE DESC

---------PRODUCTS WITH NO SALE IN THE LAST QUARTER-----------
SELECT PRODUCT, SUM (TOTAL_SALES) AS GRAND_TOTAL_SALES
FROM SALESDATACSV
WHERE PRODUCT NOT IN ('QUARTER')
 AND ORDERDATE >= DATEADD (QUARTER, -1, GETDATE ())
 GROUP BY PRODUCT
 ORDER BY GRAND_TOTAL_SALES DESC